export const Categories = 'Categories'
export const VegetableProportion = 'VegetableProportion'
export const FruitProportion = 'FruitProportion'
export const Tags = 'Tags'
export const Results = 'Results'
export const Success = 'Success'
