export const PostCode = 'PostCode'
export const NumberOfChildren = 'NumberOfChildren'
export const Ages = 'Ages'
export const Projects = 'Projects'
export const Phone = 'Phone'
export const Confirmation = 'Confirmation'
